NbcampUnreal/2nd-Team2-Final-Project

CR4S.uproject, Content/CR4S/_MonsterAI/BP_TestMonsterAttrComp.uasset, Content/CR4S/_MonsterAI/Data/Unreal_MonsterAttributeComponent.csv, Content/CR4S/_MonsterAI/Data/Unreal_MonsterAttributeComponent.uasset, Source/CR4S/MonsterAI/Components/MonsterAttributeComponent.cpp, Source/CR4S/MonsterAI/Components/MonsterAttributeComponent.h, Source/CR4S/MonsterAI/Data/MonsterAttributeRow.cpp, Source/CR4S/MonsterAI/Data/MonsterAttributeRow.h
1. csv 파일 추가
2. MonsterAttribute 초기화 함수 추가
=> [Add] Monster Attribute Component

Source/CR4S/MonsterAI/Components/MonsterPerceptionComponent.cpp, Source/CR4S/MonsterAI/Components/MonsterPerceptionComponent.h
1. 시각 기능 추가
2. 청각 기능 추가
3. 인지 범위 들어오고 놓쳤을 때 델리게이트 추가
=> [Add] Monster Perception Component

Source/CR4S/MonsterAI/Components/MonsterAttributeComponent.cpp, Source/CR4S/MonsterAI/Components/MonsterAttributeComponent.h, Source/CR4S/MonsterAI/Data/MonsterDataSubsystem.cpp, Source/CR4S/MonsterAI/Data/MonsterDataSubsystem.h
=> [Fix] Modify Monster Attribute Component

Content/CR4S/_Blueprint/FrameWork/GameMode/BP_C4MenuGameMode.uasset, Content/CR4S/_Blueprint/FrameWork/GameMode/BP_C4SurvivalGameMode.uasset, Content/CR4S/_Blueprint/UI/BP_SurvivalHUD.uasset, Content/CR4S/_Blueprint/UI/WBP_TimeDisplayWidget.uasset, Content/CR4S/_Level/MenuLevel.umap, Content/CR4S/_Level/SurvivalLevel.umap, Source/CR4S/Game/System/WorldTimeManager.cpp, Source/CR4S/Game/System/WorldTimeManager.h, Source/CR4S/UI/InGame/SurvivalHUD.cpp, Source/CR4S/UI/InGame/SurvivalHUD.h, Source/CR4S/UI/InGame/TimeDisplayWidget.cpp, Source/CR4S/UI/InGame/TimeDisplayWidget.h
1. 인 게임 HUD 클래스 SurvivalHUD 추가
2. 게임 시간 상태 확인용 TimeDisplayWidget 추가
- 디버깅용으로 날짜, 분, 초에 해당하는 숫자만 업데이트
- 추후 시계 형태로 구현 예정
=> [Add] InGame SurvivalHUD Class and TimeDisplayWidget Class

Content/CR4S/_Blueprint/MonsterAI/Data/HiemsSkillDataTable.uasset, Content/CR4S/_Blueprint/MonsterAI/Data/KamishSkillDataTable.uasset, Content/CR4S/_Blueprint/MonsterAI/Data/MonsterAttributeDataTable.uasset
[수정한 내용]
- 몬스터 데이터데이블 uasset 깨진 부분 다시 로드
- MonsterAttributeDataTable
- KamishSkillDataTable
- HiemsSkillDataTable
=> [Fix] Monster DataTable

Content/CR4S/_Blueprint/FrameWork/Manager/BP_EnvironmentManager.uasset, Content/CR4S/_Level/SurvivalLevel.umap, Source/CR4S/Game/System/EnvironmentManager.cpp, Source/CR4S/Game/System/EnvironmentManager.h, Source/CR4S/Game/System/EnvironmentalModifierVolume.cpp, Source/CR4S/Game/System/EnvironmentalModifierVolume.h
1. **EnvironmentalModifierVolume 동적 스폰 기능 추가**  
- `EnvironmentManager`를 통해 `AEnvironmentalModifierVolume`을 동적으로 생성할 수 있는 함수 추가  
- 볼륨 생성 시 다음의 파라미터 설정 가능:  
- 위치(Location)  
- 캡슐 반지름(Radius) 및 높이(Height)  
- 온도/습도 델타값(TemperatureDelta / HumidityDelta)  
- 델타 적용 속도(ChangeSpeed)  
- 지속 시간(Duration)  
- 스폰 이후 자동으로 캡슐 컴포넌트의 콜리전 설정을 활성화하여 `Overlap` 이벤트가 정상 작동되도록 처리  
2. **볼륨의 수명과 온도 상태 복구 로직 구현**  
- `Duration`이 설정된 경우: 일정 시간이 지난 후 `Destroy()` 되며 `EndOverlap` 호출 → 온도/습도 원상복구  
- `Duration`이 음수(무제한)인 경우: 수동으로 `Destroy()` 시 동일하게 `EndOverlap` 호출되어 상태 복원 처리됨  
---
- `Overlap` 시 `UEnvironmentalStatusComponent`를 가진 액터에만 영향 적용    
- 추후 다양한 타입의 볼륨을 위한 파생 클래스 혹은 파라미터 구조 개선 고려 가능  
- 볼륨 생성 함수 이름은 EnvironmentManager 클래스의 SpawnEnvModVol
=> [Update] Spawning EnvironmentalModifierVolume Features

Content/CR4S/_Blueprint/Animal/AI/BB_AnimalMonster.uasset, Content/CR4S/_Blueprint/Animal/Test/BP_TestAnimalLevelGameMode.uasset, Content/CR4S/_Blueprint/Character/Robot/ABP_Robot.uasset, Content/CR4S/_Blueprint/Character/Robot/ABP_Robot1.uasset, Content/CR4S/_Blueprint/Character/Robot/BP_LegManager.uasset, Content/CR4S/_Blueprint/Character/Robot/BP_LegManager2.uasset, Content/CR4S/_Blueprint/Character/Robot/BP_Robot.uasset, Content/CR4S/_Blueprint/Character/Robot/BP_Robot1.uasset, Content/CR4S/_Blueprint/Character/Robot/E_Robot1Legs.uasset, Content/CR4S/_Blueprint/Character/Robot/FootStepCurve.uasset, Content/CR4S/_Blueprint/Character/Robot/IK_Robot1.uasset, Content/CR4S/_Blueprint/Character/Robot/Robot1.uasset, Content/CR4S/_Blueprint/Character/Robot/Robot1_PhysicsAsset.uasset, Content/CR4S/_Blueprint/Character/Robot/Robot1_Skeleton.uasset, Content/CR4S/_Blueprint/Character/Robot/Robot1_Skeleton2.uasset, Content/CR4S/_Blueprint/Character/Robot/Robot_Anim.uasset, Source/CR4S/Character/Characters/ModularRobot.cpp, Source/CR4S/Character/Characters/ModularRobot.h, Source/CR4S/Utility/CombatStatics.cpp, Source/CR4S/Utility/CombatStatics.h, Source/CR4S/Utility/StunnableInterface.h
- 스턴을 주고 받기 위한 유틸리티 클래스 추가 
- ApplyStun : 스턴 적용
- Stun 관련 상호작용이 필요한 클래스에 상속될 인터페이스 클래스 추가 
- TakeStun : 스턴 게이지의 증감이 필요한 클래스에서 인터페이스 상속하여 구현
- 다리 관련 오류 수정된 버전으로 에셋 교체
- 에셋 교체 과정에서 BP_Robot1의 오류 발생으로 인해 로봇 BP 또한 교체
- BP_Robot 사용 요망
=> [Add] Add Stun System & Swap Robot Assets related to animation

Content/CR4S/_Blueprint/FrameWork/Manager/BP_EnvironmentManager.uasset, Source/CR4S/Game/System/EnvironmentManager.cpp, Source/CR4S/Game/System/EnvironmentManager.h, Source/CR4S/Game/System/SeasonManager.cpp, Source/CR4S/Game/System/SeasonManager.h
EnvironmentManager에 Dawn/Dusk 기반 수면 시간 판단 함수(IsSleepTime) 추가
=> [Add] IsSleepTime

Source/CR4S/Character/Components/EnvironmentalStatusComponent.cpp, Source/CR4S/Character/Components/EnvironmentalStatusComponent.h
1. 온도/습도 임계값 초과 및 정상 복귀 시 델리게이트 호출 추가
- 온도/습도가 상한선(+1), 하한선(-1)을 초과할 때 OnTemperatureBreach, OnHumidityBreach 호출
- 임계값을 벗어났던 온도/습도가 정상 범위로 돌아올 때 OnTemperatureNormalized, OnHumidityNormalized 호출
2. 최대값 최솟값 Setter 추가
=> [Update] EnvironmentalStatusComp Delegates

CR4S.uproject, Config/DefaultEngine.ini, Source/CR4S/CR4S.Build.cs
1. **스팀 OSS 연동**  
- OnlineSubsystemSteam 연동을 위해 빌드 모듈 및 플러그인 설정 추가
---
- 향후 Steam API 기능 사용을 대비하여 관련 파일(steam_api.dll, steam_appid.txt) 공유 완료
- Steam 클라이언트 실행 중일 경우 오버레이를 통해 연동 상태 확인 가능
=> [Update] Add Online Subsystem Steam

Content/CR4S/_Map/MainMap.umap, Content/DeepElderCaves/Maps/Demonstration.umap, Content/LavaCave/Maps/Cave_Map.umap, Content/ProceduralNaturePack/Meshes/water/river-plane-a.uasset, Content/ProceduralNaturePack/Spline_BluePrints/master_river_spline.uasset, Content/SoulCave/Maps/LV_Soul_Cave.umap
- 물 콜리전 제거
- 접근 불가 지역 블로킹 볼륨 추가
- 용암 및 돌 지형 수정
- 산/강 숫자 제거
- 나무 배치 추가
- 날씨 배치
=> Level Update

Content/CR4S/_Blueprint/FrameWork/GameMode/BP_C4MenuGameMode.uasset, Content/CR4S/_Map/MainMap.umap
=> [Add] Level Setting (Temperature, Humidity)

Source/CR4S/Gimmick/GimmickObjects/ItemPouchGimmick.cpp, Source/CR4S/Gimmick/UI/BedWidget.cpp, Source/CR4S/Gimmick/UI/BedWidget.h
- 세이브 로직 침대 위젯과 연동
- 아이템 주머니 cpp 파일에 필요없는 헤더 제거
=> [Update] Save Logic Connect Bed Widget / [BugFix] Item Pouch BugFix

Source/CR4S/MonsterAI/BaseMonster.h, Source/CR4S/MonsterAI/Components/MonsterSkillComponent.cpp, Source/CR4S/MonsterAI/Components/MonsterSkillComponent.h, Source/CR4S/MonsterAI/Components/MonsterStateComponent.cpp, Source/CR4S/MonsterAI/Components/MonsterStateComponent.h, Source/CR4S/MonsterAI/Controller/SeasonBossMonsterAIController.cpp, Source/CR4S/MonsterAI/Controller/SeasonBossMonsterAIController.h
1. 스턴 중 스킬 즉시 중단
- MonsterStateComponent에서 스턴 시작, 스턴 종료 델리게이트 추가해서 스턴 중 스킬 중단 관리했씁니다
- 일단 계절보스는 스폰하는 액터가 주공격이기에 계절보스 AI 컨트롤러에서 구현했습니다
=> [Add] Stop the stun attack

Source/CR4S/Game/System/SpawnZoneVolume.cpp, Source/CR4S/Game/System/SpawnZoneVolume.h
=> [Update] Spawn Logic

Content/CR4S/_Data/Item/DT_ItemRecipeData.uasset, Content/EasyBuildingSystem/Blueprints/UserInterface/UI_EBS_MalletMenu.uasset, Content/EasyBuildingSystem/Blueprints/UserInterface/UI_EBS_ResourceValue.uasset, Source/CR4S/Character/Characters/PlayerCharacter.cpp, Source/CR4S/Game/SaveGame/SaveGameManager.cpp, Source/CR4S/Gimmick/Data/ItemData.h, Source/CR4S/Gimmick/Manager/ItemGimmickSubsystem.cpp, Source/CR4S/Gimmick/Manager/ItemGimmickSubsystem.h, Source/CR4S/Inventory/Components/PlayerInventoryComponent.h
- 플레이어 사망시 인벤토리 닫히도록 수정
- 건축 모드 UI 텍스트 한글로 변경
- 게임 로드시 플레이어 인벤토리 초기화 버그 수정
- 동물성 재료가 들어가는 레시피 수정
=> [BugFix] Inventory Reset When Load Game

Content/CR4S/_Art/Texture/UI/T_GuideBorder.uasset, Content/CR4S/_Blueprint/UI/InGame/WBP_DefaultInGameWidget.uasset, Content/CR4S/_Blueprint/UI/InGame/WBP_GuideWidget.uasset, Source/CR4S/Game/GameMode/C4SurvivalGameMode.cpp, Source/CR4S/UI/InGame/DefaultInGameWidget.cpp, Source/CR4S/UI/InGame/DefaultInGameWidget.h, Source/CR4S/UI/InGame/GuideWidget.cpp, Source/CR4S/UI/InGame/GuideWidget.h, Source/CR4S/UI/InGame/SurvivalHUD.cpp, Source/CR4S/UI/InGame/SurvivalHUD.h
1. DefaultInGameWidget 클래스에 GuidWidget 추가
- 위젯 애니메이션으로 토글 구현
2. GameMode에서 게임 시작 시 직접 토글해주는데, 추후 전용 매니저 생성 예정
=> [Add] GuideWidget in DefaultInGameWidget

CR4S.uproject, Source/CR4S/Character/Characters/ModularRobot.cpp, Source/CR4S/Character/Components/ModularRobotStatusComponent.cpp, Source/CR4S/Character/Components/ModularRobotStatusComponent.h
- 호버링 관련 TimelineComponent 캐싱용 포인터 ModularRobotStatusComponent에 추가
- BeginPlay()에서 캐싱용 TimelineComponent 초기화
- ModularRobotStatusComponent에서 StopHover() 함수 호출시 함께 'TimelineComponent->Stop()' 호출하도록 수정
=> [Fix] Infinite hovering after resource exhaustion

Content/CR4S/_Level/UserTestLevel.umap
=> Add : UserTestLevel

Content/MechanicGirl/Mesh/UE4_Girl.uasset, Content/MechanicGirl/Mesh/UE4_Mannequin_Skeleton.uasset, Plugins/ALS-Refactored-4.15/Content/ALS/Animations/Base/A_Als_Idle.uasset, Plugins/ALS-Refactored-4.15/Content/ALS/Animations/Overlays/Other/A_Als_Default_Poses.uasset, Plugins/ALS-Refactored-4.15/Content/ALS/Character/CR_Als1.uasset, Plugins/ALS-Refactored-4.15/Content/ALS/Character/SK_Als.uasset
- 메시 기존 ALS 메시로 교체
- ALS, 커스텀 캐릭터 모두 root, hand(l,r), ik는 Animation
- pelvis는 Animation scaled
- 나머지는 skeleton으로 설정
=> [Fix] Corrected bent leg animation error in Idle state

Source/CR4S/MonsterAI/Components/MonsterStateComponent.cpp
- 기절 걸렸을 때 idle 로 복귀하는 부분을 이전 상태로 복귀하도록 수정했습니다. 간단한 상태 변경 로그를 추가해놨습니다.
=> [Fix] Feature/monster/season/season detail
